name: Deploy lambda to AWS
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.10'
            
            - name: Install Libraries
              run: |
                    cd function
                    python -m pip install --upgrade pip
                    if [ -f requirements ]; then pip install -r requirements.txt .; fi
            
            - name: Create zip bundle
              run: |
                    cd function
                    zip -r ../${{ github.sha }}.zip .
            
            - name: Archive artifact
              uses: actions/upload-artifact@v3
              with:
                name: zipped-bundle
                path: ${{ github.sha }}.zip
            
    upload:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v3
              with:
                name: zipped-bundle
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            - name: Upload to S3
              run: aws s3 cp ${{ github.sha }}.zip s3://lambda-artifacts-gl/${{ github.sha }}.zip
    
    deploy:
        runs-on: ubuntu-latest
        needs: upload
        steps: 
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            - name: Update function code
              run: |
                    aws lambda update-function-code \
                    --function-name my-function \
                    --s3-bucket lambda-artifacts-gl \
                    --s3-key ${{ github.sha }}.zip
                    --publish
